version: "3.3"

services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "443:443"
      - "8080:8080"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik/traefik.config.toml:/etc/traefik/traefik.config.toml:ro
      - ./certs:/etc/certs:ro
    networks:
      mynet:
        ipv4_address: 192.168.220.84
  php5:
    image: anapassos/php5:latest
    container_name: php5
    labels:
      - traefik.http.routers.php5.rule=Host(`php5.localhost`)
      - traefik.http.routers.php5.entrypoints=https
      - traefik.http.routers.php5.tls=true
    volumes:
      - ./php5/www:/var/www
    networks:
      mynet:
        ipv4_address: 192.168.220.85
  php7:
    image: anapassos/php7:latest
    container_name: php7
    labels:
      - traefik.http.routers.php7.rule=Host(`php7.localhost`)
      - traefik.http.routers.php7.entrypoints=https
      - traefik.http.routers.php7.tls=true
    volumes:
      - ./php7/www:/var/www/html
    networks:
      mynet:
        ipv4_address: 192.168.220.86
networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.220.0/24
