[http.middlewares]
  [http.middlewares.redirect.redirectscheme]
    scheme = "https"

[tls]
  [[tls.certificates]]
    certFile = "/etc/certs/local-traefik-cert.pem"
    keyFile = "/etc/certs/local-traefik-key.pem"